### Upgrade ###################################################################

- apt: upgrade=dist update_cache=yes cache_valid_time=3600

### Locale Configuration ######################################################

- command: locale-gen --purge en_US.UTF-8

- name: Setup locale config to en_US.UTF-8
  copy: src=locale dest=/etc/default/locale
  register: setup_locale_config

- name: Update locale
  command: /usr/sbin/update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
  register: updated_locale
  when: setup_locale_config.changed


### Timezone Configuration ####################################################

- name: Setup timezone config Set timezone to UTC
  copy: src=timezone dest=/etc/timezone
  register: setup_timezone_config

- name: Reconfigure tzdata
  shell: dpkg-reconfigure -f noninteractive tzdata
  when: setup_timezone_config.changed

### ntpdate ###################################################################

- apt: pkg=ntpdate state=latest update_cache=yes cache_valid_time=3600

- name: Setup daily ntpdate config
  template: src=ntpdate_daily
            dest=/etc/cron.daily/ntpdate
            mode=0755
  register: setup_daily_ntpdate_config

- name: Initial ntpdate sync
  shell: /etc/cron.daily/ntpdate
  when: setup_daily_ntpdate_config.changed

### NTP Configuration #########################################################

- apt: pkg=ntp state=latest update_cache=yes cache_valid_time=3600
  when: ntp_enabled

- apt: pkg=ntp state=absent update_cache=yes cache_valid_time=3600
  when: not ntp_enabled

- template: src=ntp.conf
            dest=/etc/ntp.conf
            mode=0644
  register: setup_ntp_config

- service: name=ntp
           state=restarted
  when: ntp_enabled and setup_ntp_config.changed

- service: name=ntp
           state=started
  when: ntp_enabled


### Vim as default editor #####################################################

- name: Install vim-nox
  apt: pkg=vim-nox state=latest update_cache=yes cache_valid_time=3600
  register: install_vim_nox

- name: Set vim-nox as default editor
  command: update-alternatives --set editor /usr/bin/vim.nox
  when: install_vim_nox.changed


### vi shell behavior #########################################################

- template:
    mode: 0644
    src: profile_vi.sh
    dest: /etc/profile.d/vi.sh

- lineinfile:
   line: syntax on
   state: present
   dest: /etc/vim/vimrc.local
   create: yes
   mode: 0644

### Install Other #############################################################

- name: Install other things for ansible
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - python-pycurl


### Etc keeper ################################################################

- template: src=root_gitconfig
            dest=~/.gitconfig

- name: Etc keeper install packages
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - etckeeper
    - git

- name: Etc keeper uninitialize bzr (in case)
  command: etckeeper uninit -f
           removes=/etc/.bzr

- name: Etc keeper configuration for git
  copy: src=etckeeper.conf
        dest=/etc/etckeeper/etckeeper.conf

- name: Etc keeper initialize with git
  shell: etckeeper init && etckeeper commit 'initial commit'
         creates=/etc/.git


### monit #####################################################################

- apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - monit

- template: src=monit_defaults
            dest=/etc/monit/conf.d/defaults
            mode=0700
  register: monit_default_config

- service:
    name: monit
    state: restarted
  when: monit_default_config.changed

- service:
    name: monit
    state: started


### manage authorized keys ####################################################

- authorized_key: user=root
                  key="{{item}}"
  with_items: ssh_keys

- authorized_key: user=root
                  key="{{item}}"
                  state=absent
  with_items: removed_ssh_keys


